# Generated by Django 5.0.4 on 2024-04-06 21:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.IntegerField(choices=[(0, 'Docker Image')])),
                ('link', models.CharField(max_length=500)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'In processing'), (2, 'Processed'), (3, 'Rejected'), (4, 'Approved'), (-1, 'Invalid')], default=0, editable=False)),
                ('has_json', models.BooleanField(default=False, editable=False)),
                ('has_html', models.BooleanField(default=False, editable=False)),
                ('repo_digests', models.TextField(editable=False)),
                ('short_report_info', models.TextField(editable=False)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_approved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('security', 'Can approve / reject request'),),
            },
        ),
    ]
