version: '3'

services:
  registry:
    image: registry:latest
    restart: always
    ports:
      - 5002:5000
    volumes:
      - ./data:/var/lib/registry

#    volumes:docker pull registry:latest
#docker pull mysql@sha256:4552fcc5d3cdb8cdee76ee25cce28bf60b0eb3ce93d25ba3bfff7a66bfdcdee8
#docker tag mysql@sha256:4552fcc5d3cdb8cdee76ee25cce28bf60b0eb3ce93d25ba3bfff7a66bfdcdee8 localhost:5002/mysql4552fcc5d3cd
#docker push localhost:5002/mysql4552fcc5d3cd
#curl -X GET http://localhost:5002/v2/_catalog