version: '3'

services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4030:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx_logs:/var/log/nginx
    depends_on:
      - trivy

  trivy:
    image: aquasec/trivy
    entrypoint: trivy server --listen 0.0.0.0:4030 --token dummy
    volumes:
      - ./trivy-data/trivy/db:/root/.cache/trivy/db
