version: '3.8'

services:
  django:
    build:
      context: ./django
    ports:
      - '80:8000'
    volumes:
      - ./django:/opt/app
      - database:/opt/database
      - reports:/opt/reports
      - logs:/opt/logs
    env_file:
      - ./django/.env
    restart: always
  trivy:
    build:
      context: ./trivy
    expose:
      - 8080
    volumes:
      - ./trivy:/opt/app
      - reports:/opt/reports
    env_file:
      - ./trivy/.env
    restart: always
  docker:
    build:
      context: ./docker
    privileged: true
    expose:
      - 8080
    volumes:
      - ./docker:/opt/app
      - reports:/opt/reports
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

volumes:
  reports:
  database:
  logs: